Fix/tc sram
pulp-platform/tech_cells_generic pull request #20
Opened 2022-02-07 13:11 UTC by JeanRochCoulon

Hello @micprog, I would be pleased to use the project to model the cva6 memories, as seen with @zarubaf. The cva6 regression was failing, I have made some fixes to make it PASS:
- 2 fixes to suit Verilator (Verilator errors are in the commit message)
- 1 fix detected by VCS
- 1 improvement to speed-up init time
Tell me !

2022-02-12 14:11 UTC, niwis requested changes
@JeanRochCoulon thank you for the contribution! Could you perhaps elaborate on the errors that you encounter and how the changes resolve them?

2022-02-12 14:11 UTC, niwis commented on src/rtl/tc_sram.sv
> +  always @(posedge clk_i or negedge rst_ni) begin
Why change from `always_ff` to `always`? This still looks like a sequential block to me

2022-02-12 14:11 UTC, niwis commented on src/rtl/tc_sram.sv
> +        sram[i] = init_val[i];
Blocking and non-blocking assignments should never be mixed in the same block (ref. https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#blocking-and-non-blocking-assignments)

2022-02-15 15:10 UTC, JeanRochCoulon commented on src/rtl/tc_sram.sv
> +  always @(posedge clk_i or negedge rst_ni) begin
I am ok, I reverted the modification

2022-02-15 15:11 UTC, JeanRochCoulon commented on src/rtl/tc_sram.sv
> +        sram[i] = init_val[i];
As Verilator produced the following error, I modified all the '<=' into '='

Fix Unsupported feature by Verilator: Delayed assignment to array inside for loops
    
    %Error-BLKLOOPINIT: /home/jrcoulon/Projects/spritz-core-v/spritz/core-v-verif/core-v-cores/cva6//core/tech_cells_generic/src/rtl/tc_sram.sv:128:17: Unsupported: Delayed assignment to array inside for loops (non-delayed is ok - see docs)
      128 |         sram[i] <= init_val[i];
          |                 ^~

2022-02-15 15:13 UTC, JeanRochCoulon commented
Thanks a lot @niwis for the feedback, I modified (with push --force) the PR.
Note: The timing optimization has not been pushed again, maybe I will submit another PR with it.

2022-04-20 09:31 UTC, JeanRochCoulon commented
Hello @niwis, I have updated the model. This tc_sram model has been used and verified in a coming CVA6 PR, to submit this CVA6 PR I need that this tc_sram PR merged. Thanks for your review !!

2022-04-28 09:25 UTC, closed without merging