Performance optimization of tc_sram init
pulp-platform/tech_cells_generic pull request #24
Opened 2022-06-16 09:11 UTC by JeanRochCoulon

tc_sram init takes too many time. Thsi is a fix. My CVA6 simulation takes 1'25'' with current version, and 31'' with the proposal.

2022-06-16 09:12 UTC, JeanRochCoulon commented
@meggiman @niwis

2022-07-26 07:01 UTC, JeanRochCoulon commented
Hello @meggiman @niwis 
This PR is open since June 16th. I need it in CVA6 project to speed-up simulations. Could you have a look please ?
Kind regards

2022-07-26 09:39 UTC, niwis approved these changes
Sorry, I missed the PR. Looks good to me!

2022-07-26 09:45 UTC, niwis requested changes

2022-07-26 09:45 UTC, niwis commented on src/rtl/tc_sram.sv
>          endcase
One formatting nitpick: Could you fix the indentation for these lines?

2022-07-26 12:56 UTC, JeanRochCoulon commented on src/rtl/tc_sram.sv
>          endcase
@niwis.   Done ! Thank you for your review

2022-07-26 14:24 UTC, niwis approved these changes

2022-07-26 14:26 UTC, merged

2022-07-26 15:36 UTC, JeanRochCoulon commented
Merci !